<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-KNL22F4G" failures="0" tests="2" name="testPackage.LoginTestCase" time="4.149" errors="1" timestamp="2023-08-03T16:00:01 IST" skipped="0">
  <testcase classname="testPackage.LoginTestCase" name="validloginMethod" time="2.914"/>
  <testcase classname="testPackage.LoginTestCase" name="inValidLoginMethod" time="1.235">
    <error message="org.apache.poi.xssf.usermodel.XSSFWorkbookFactory not found - check if poi-ooxml-*.jar is on the classpath." type="java.io.IOException">
      <![CDATA[java.io.IOException: org.apache.poi.xssf.usermodel.XSSFWorkbookFactory not found - check if poi-ooxml-*.jar is on the classpath.
at org.apache.poi.ss.usermodel.WorkbookFactory.initFactory(WorkbookFactory.java:351)
at org.apache.poi.ss.usermodel.WorkbookFactory.initXssf(WorkbookFactory.java:336)
at org.apache.poi.ss.usermodel.WorkbookFactory.create(WorkbookFactory.java:255)
at org.apache.poi.ss.usermodel.WorkbookFactory.create(WorkbookFactory.java:221)
at genericPackage.Flib.getLastRowCount(Flib.java:32)
at testPackage.LoginTestCase.inValidLoginMethod(LoginTestCase.java:33)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
    <system-out>
      <![CDATA[This method failed taken ScreenShot : inValidLoginMethod]]>
    </system-out>
  </testcase> <!-- inValidLoginMethod -->
  <system-out>
    <![CDATA[This method failed taken ScreenShot : inValidLoginMethod]]>
  </system-out>
</testsuite> <!-- testPackage.LoginTestCase -->
